# Generated by Django 5.2.14 on 2026-05-26 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadedcsv',
            old_name='csv_file',
            new_name='file',
        ),
        migrations.RemoveField(
            model_name='uploadedcsv',
            name='source_type',
        ),
        migrations.RemoveField(
            model_name='uploadedcsv',
            name='title',
        ),
        migrations.AddField(
            model_name='uploadedcsv',
            name='category',
            field=models.CharField(choices=[('sap', 'SAP'), ('utility', 'Utility'), ('travel', 'Travel')], default='sap', max_length=50),
        ),
    ]
