# Generated by Django 5.2.14 on 2026-05-26 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0002_rename_csv_file_uploadedcsv_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedcsv',
            name='is_processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='uploadedcsv',
            name='original_filename',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='uploadedcsv',
            name='source_of_truth',
            field=models.CharField(default='manual_upload', max_length=100),
        ),
        migrations.AlterField(
            model_name='uploadedcsv',
            name='category',
            field=models.CharField(choices=[('sap', 'SAP'), ('utility', 'UTILITY'), ('travel', 'TRAVEL')], max_length=50),
        ),
    ]
