# Generated by Django 5.2.14 on 2026-05-26 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('emmision', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewer_note', models.TextField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(auto_now_add=True)),
                ('emission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emmision.emissionrecord')),
            ],
        ),
    ]
