# Generated by Django 5.2.14 on 2026-05-26 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewlog',
            name='emission',
        ),
        migrations.AddField(
            model_name='reviewlog',
            name='action',
            field=models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected')], default='approved', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reviewlog',
            name='emission_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reviewlog',
            name='reviewer_note',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
    ]
