# Generated by Django 5.2.14 on 2026-05-26 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emmision', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emissionrecord',
            old_name='created_at',
            new_name='uploaded_at',
        ),
        migrations.RenameField(
            model_name='emissionrecord',
            old_name='quantity',
            new_name='value',
        ),
        migrations.RemoveField(
            model_name='emissionrecord',
            name='category',
        ),
        migrations.RemoveField(
            model_name='emissionrecord',
            name='emission_value',
        ),
        migrations.RemoveField(
            model_name='emissionrecord',
            name='source_type',
        ),
        migrations.AddField(
            model_name='emissionrecord',
            name='date',
            field=models.DateField(default='2026-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emissionrecord',
            name='is_edited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='emissionrecord',
            name='original_source',
            field=models.CharField(default='unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='emissionrecord',
            name='source',
            field=models.CharField(default='electricity', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='emissionrecord',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
